name: vision
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.0
  webview_flutter: ^0.3.11+3
  flutter_launcher_icons: ^0.7.2+1
  firebase_auth: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/joy.jpg
     - images/hilltop_vision.png
     - images/vic.jpg
     - images/team.jpg
     - images/twitter.png
     - images/facebook.png
     - images/instagram.png
     - images/hilltop_online_radio.jpg
     - images/join_the_resonance.jpg
     - images/me_before_you.jpg
     - images/hilltop_follow.jpg
     - images/social_media_platforms.png
     - images/outreach_icon.jpg
     - images/radio_icon.jpg
     - images/events_icon.jpg
     - images/Great_I_Am.jpg
     - images/1000words.jpg
     - images/Levitate Show.jpg
     - images/Christeenager.jpg
     - images/Be_Ye_Transformed.jpg
     - images/Beast_mode.jpg
     - images/Peter_Ojum.jpg
     - images/Trap_and_Grace.jpg
     - images/the_fifth.jpg
     - images/hustle_1.jpg
     - images/hustle_2.jpg
     - images/hustle_3.jpg
     - images/summer_thank_you.jpg
     - images/at_the_altar.jpg
     - images/what-are_you_eating.jpg
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
